name: Create Vercel Preview URL on Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Biome
        run: npm run lint

  build_and_deploy:
    name: Build and Deploy to Vercel
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}

      # - name: preview-url
      #   run: |
      #     echo ${{ steps.vercel-deploy.outputs.preview-url }}
